#! /usr/bin/env ruby

require 'pg'

def display_expences_list
  db = PG.connect(dbname: "expenses")
  sql_query = 'SELECT * FROM expenses'
  result = db.exec sql_query

  result.each do |tupple|
    row = [tupple['id'].rjust(4), tupple['created_on'].rjust(10), tupple['amount'].rjust(12), tupple['memo']]
    puts row.join(' | ')
  end
end

def display_help
  puts <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - records a new expense
    clear - delete all expenses
    list - lists all expenses
    delete NUMBER - removes expenses with id NUMBER
    search QUERY - lists expenses with a matching memo field
  HELP
end

command = ARGV.first

case command
when 'list' then display_expences_list
else
  display_help
end
